# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

import os, yaml
import xml.etree.ElementTree as ET
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, DeclareLaunchArgument, ExecuteProcess
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, TextSubstitution, Command
from launch.conditions import IfCondition
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from ament_index_python.packages import get_package_share_directory


def _strip_xml_whitespace(element):
    if element.text and not element.text.strip():
        element.text = None
    if element.tail and not element.tail.strip():
        element.tail = None
    for child in list(element):
        _strip_xml_whitespace(child)


def generate_launch_description():
    rname = LaunchConfiguration("rname")
    show_depth_debug = LaunchConfiguration("show_depth_debug")
    wname = LaunchConfiguration("wname")
    robot_name = ParameterValue(Command(["echo -n ", rname]), value_type=str)
    gazebo_model_name = ParameterValue(Command(["echo -n ", rname, "_gazebo"]), value_type=str)

    # Generate xacro → URDF, write to temp YAML params file
    # This avoids passing huge XML on the command line (-- breaks rcl parser)
    go2_share = get_package_share_directory("go2_description")
    import subprocess, tempfile
    xacro_path = os.path.join(go2_share, "xacro", "robot.xacro")
    urdf = subprocess.check_output(["xacro", xacro_path], text=True)
    # gazebo_ros2_control forwards robot_description through ROS arguments.
    # Keep it as a single XML string without comments/newlines so rcl's parser
    # does not trip over xacro's autogenerated header or embedded comments.
    urdf_root = ET.fromstring(urdf)
    _strip_xml_whitespace(urdf_root)
    urdf = ET.tostring(urdf_root, encoding="unicode", short_empty_elements=True)
    params_file = os.path.join(tempfile.gettempdir(), "go2_rsp_params.yaml")
    with open(params_file, 'w') as f:
        yaml.dump({"/**": {"ros__parameters": {"robot_description": urdf}}}, f, width=99999)

    robot_state_publisher_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="screen",
        arguments=["--ros-args", "--params-file", params_file],
    )

    gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(get_package_share_directory("gazebo_ros"), "launch", "gazebo.launch.py")
        ),
        launch_arguments={
            "world": [
                os.path.join(get_package_share_directory("rl_sar"), "worlds", ""),
                wname,
                ".world",
            ],
        }.items(),
    )

    spawn_entity = Node(
        package="gazebo_ros",
        executable="spawn_entity.py",
        arguments=[
            "-topic", "/robot_description",
            "-entity", "robot_model",
            "-z", "0.42",
        ],
        output="screen",
    )

    joy_node = Node(
        package='joy',
        executable='joy_node',
        name='joy_node',
        output='screen',
        parameters=[{
            'deadzone': 0.1,
            'autorepeat_rate': 0.0,
        }],
    )

    param_node = Node(
        package="demo_nodes_cpp",
        executable="parameter_blackboard",
        name="param_node",
        parameters=[{
            "robot_name": robot_name,
            "gazebo_model_name": gazebo_model_name,
        }],
    )

    depth_debug_viewer = ExecuteProcess(
        cmd=[
            "python3",
            os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "scripts", "depth_debug_viewer.py"),
        ],
        output="screen",
        condition=IfCondition(show_depth_debug),
    )

    return LaunchDescription([
        DeclareLaunchArgument(
            "wname",
            description="World name (e.g., flat, stairs, earth)",
            default_value=TextSubstitution(text="flat"),
        ),
        DeclareLaunchArgument(
            "rname",
            description="Robot name (e.g., a1, go2)",
            default_value=TextSubstitution(text=""),
        ),
        DeclareLaunchArgument(
            "show_depth_debug",
            description="Show raw and processed depth images",
            default_value=TextSubstitution(text="true"),
        ),
        robot_state_publisher_node,
        gazebo,
        spawn_entity,
        joy_node,
        param_node,
        depth_debug_viewer,
    ])
